/* creacion de la tabla jornada  */
drop table jornada cascade constraints;
create table jornada(
    id_jornada NUMBER(4) GENERATED BY DEFAULT AS IDENTITY (START WITH 1 INCREMENT BY 1),
    fecha date,
    constraint pk_id_jornada primary key(id_jornada)
);


/* creacion de la tabla equipo  */
drop table equipo cascade constraints;
create table equipo(
    id_equipo number(4) GENERATED BY DEFAULT AS IDENTITY (START WITH 1 INCREMENT BY 1),
    nombre_equipo varchar2(50),
    puntos number(3) default 0,
    partidos_jugados number(3) default 0,
    partidos_ganados number(3) default 0,
    partidos_perdidos number(3) default 0,
    estado varchar2(1) default 'A',
    constraint pk_id_equipo primary key(id_equipo),
    constraint ck_estado check(upper(estado) in('A','C'))
);

/* creacion de la tabla partido  */
drop table partido cascade constraints;
create table partido(
    id_partido NUMBER(4) GENERATED BY DEFAULT AS IDENTITY (START WITH 1 INCREMENT BY 1),
    hora varchar2(10),
    id_jornada number(4),
    id_equipo1 number(4),
    id_equipo2 number(4),
    equipo_ganador number(4),
    constraint pk_id_partido primary key(id_partido),
    constraint fk_id_jornada foreign key(id_jornada) references jornada,
    constraint fk_id_equipo1 foreign key(id_equipo1) references equipo,
    constraint fk_id_equipo2 foreign key(id_equipo2) references equipo,
    constraint fk_equipo_ganador foreign key(equipo_ganador) references equipo
);


/* creacion de la tabla persona  */
drop table persona cascade constraints;
create table persona(
    id_persona number(4) GENERATED BY DEFAULT AS IDENTITY (START WITH 1 INCREMENT BY 1),
    nombre varchar2(40),
    apellido varchar2(40),
    constraint pk_id_persona primary key(id_persona)
);

/* creacion de la tabla jugador  */
drop table jugador cascade constraints;
create table jugador(
    id_persona number(4),
    apodo varchar2(40),
    rol varchar2(20),
    sueldo number(10),
    id_equipo number(4),
    constraint pk_id_jugador primary key(id_persona),
    constraint fk_id_jugador foreign key(id_persona) references persona,
    constraint ck_sueldo check(sueldo >= 1000),
    constraint fk_id_j_equipo foreign key(id_equipo) references equipo
);


/* creacion de la tabla entrenador  */
drop table entrenador cascade constraints;
create table entrenador(
    id_persona number(4),
    id_equipo number(4),
    constraint pk_id_entrenador primary key(id_persona),
    constraint fk_id_entrenador foreign key(id_persona) references persona,
    constraint fk_id_e_equipo foreign key(id_equipo) references equipo
);



/* creacion de la tabla asistente  */
drop table asistente cascade constraints;
create table asistente(
    id_persona number(4),
    id_equipo number(4),
    constraint pk_id_asistente primary key(id_persona),
    constraint fk_id_asistente foreign key(id_persona) references persona,
    constraint fk_id_a_equipo foreign key(id_equipo) references equipo
);


/* creacion de la tabla duenyo  */
drop table duenyo cascade constraints;
create table duenyo(
    id_persona number(4),
    id_equipo number(4),
    constraint pk_id_duenyo primary key(id_persona),
    constraint fk_id_duenyo foreign key(id_persona) references persona,
    constraint fk_id_d_equipo foreign key(id_equipo) references equipo
);


/* creacion de la tabla login  */
drop table login cascade constraints;
create table login(
    id_login number(4) GENERATED BY DEFAULT AS IDENTITY (START WITH 1 INCREMENT BY 1),
    usuario varchar2(40),
    contrasenya varchar2(20),
    tipo varchar2(5),
    constraint pk_id_login primary key(id_login),
    constraint ck_tipo check(upper(tipo) in('USER','ADMIN'))
);


/* creacion de la tabla xml  */
drop table xml cascade constraints;
create table xml(
    id_xml number(4) GENERATED BY DEFAULT AS IDENTITY (START WITH 1 INCREMENT BY 1),
    clasificacion CLOB,
    resultado_ultima_jornada CLOB,
    constraint pk_id_xml primary key(id_xml)
);

